#!/usr/bin/env python
# coding: utf-8

# In[1]:
import xml.etree.ElementTree as ET
import string
import os  
import re


# In[2]:
def cleanhtml(raw_html):
  cleanr = re.compile('<.*?>')
  cleantext = re.sub("[^a-zA-Z]", " ", str(raw_html))

  return cleantext


# In[3]:
parent_dir_false  = "D:\\corpus_950\\false"
fulltext = "fulltext"
xml =".xml"

def getcsv(outfile, parent_dir, word):

    for root, dirs, files in os.walk(parent_dir):
        for name in files:
            if name =='fulltext.xml':
                new_path = (os.path.join(root, name))
                file_name = os.path.dirname(new_path)
                tree = ET.parse(new_path)
                root = tree.getroot()
                abstract = root.findall("./front/article-meta/abstract/")
                #print(outfile)

                for j in abstract:
                    new = (j.text)
                    new1 = cleanhtml(new)
                    new1= new1.lower()
                    input_str = re.sub(r'\d+', '', new1)
                    #input_str = input_str.translate(string.maketrans("",""), string.punctuation)
                    new_1 = input_str.strip()


                    outp = str(file_name) +  "," + new1 +  "," + word  + "\n"

                    outfile.write(outp)

    outfile.close()

# In[4]:
outfile1 = open('true.txt','w')
parent_dir_true  = "D:\\try1\\true"
word1 = "true"

getcsv(outfile1, parent_dir_true, word1)


outfile2 = open('false.txt','w')
parent_dir_false  = "D:\\try1\\false"
word2 = "false"

getcsv(outfile2, parent_dir_false, word2)


# In[5]:
parent_dir_true  = "D:\\try1\\true"
file_name = os.path.dirname(parent_dir_true)

print(file_name)


# In[6]:
def remove_abs(out_put, in_put):
    with open(in_put, "r") as a_file:
      for line in a_file:
        if len(line.split()) >2:
            out_put.write(line)

    out_put.close()
    
in_put1 = 'true.txt'
in_put2 = 'false.txt'

out_put1 = open('true_new.txt','w')
out_put2 = open('false_new.txt','w')

remove_abs(out_put1,in_put1)
remove_abs(out_put2, in_put2)


# In[7]:
# Python program to 
# demonstrate merging 
# of two files 
  
data = data2 = "" 
  
# Reading data from file1 
with open('true_new.txt') as fp: 
    data = fp.read() 
  
# Reading data from file2 
with open('false_new.txt') as fp: 
    data2 = fp.read() 
  
# Merging 2 files 
# To add the data of file2 
# from next line 
data += "\n"
data += data2 
  
with open ('OpenVirus.txt', 'w') as fp: 
    fp.write(data) 


# In[11]:
import pandas as pd
df = pd.read_fwf('OpenVirus.txt')
df.to_csv("OpenVirus.csv", sep=',')


# In[13]:
import pandas as pd

read_file = pd.read_csv (r'OpenVirus.txt')
read_file.to_csv (r'OpenVirus.csv', index=None)
